# Generated by Django 3.1.1 on 2020-09-11 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontBoard',
            fields=[
                ('boardidx', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('context', models.TextField(verbose_name='내용')),
                ('files', models.FileField(null=True, upload_to='', verbose_name='업로드파일')),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일')),
                ('deldate', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'front_board',
            },
        ),
        migrations.CreateModel(
            name='FrontComment',
            fields=[
                ('commentidx', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField(verbose_name='댓글내용')),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일')),
                ('boardidx', models.ForeignKey(db_column='boardidx', on_delete=django.db.models.deletion.DO_NOTHING, to='front.frontboard')),
            ],
            options={
                'db_table': 'front_comment',
            },
        ),
    ]
